[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install --omit=dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/api/admin"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/.netlify/functions/api/dashboard"
  status = 200

